title:             ElApseR
email:             your-email@example.com
description:       A Blog For Projects By ElApseR
author:            Hyunho Cho
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://elapser.github.io"

# Social Profiles
twitter_username:  
github_username:   ElApseR
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
