title:             "혀노의 기술 블로그"
email:             medussa2818@gmail.com
description:       Projects and Research by Hyunho Cho
author:            Hyunho Cho
baseurl:           ""
url:               "http://elapser.github.io"

# Social Profiles
twitter_username:
github_username:   ElApseR
facebook_username:
disqus_shortname: ElApseR

# Build settings
timezone:    Asia/Seoul
future:            true
markdown:          kramdown
paginate:          7
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

prose:
  rooturl: '_posts'
  siteurl: 'http://elapser.github.io'
  relativeLinks: 'http://elpaser.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Visualization"
              value: visualization
            - name: "Python"
              value: python
            - name: "Statistics"
              value: statistics
            - name: "Machine-Learning"
              value: machine_learning
            - name: "Projects"
              value: projects
            - name: "NLP"
              value: nlp
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false
